sudo: false
language: python

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - "PYPI_USERNAME=wellcomedigitalplatform"

    # This contains the following variables:
    #  - PYPI_PASSWORD
    #
    - secure: "Ts56N79krn4FwXhTFIj3uEMTrTe1H0/kAMIyPvlakkxBsbWM72pKp/wQL4Mry3XwqUJ6v5LL1fODR1L39dK28NWbjyA3RSaaW3053r9HVcflP4zoO/H5rVPdsCyw7jrYv5mimBBZO80895yFQL+DIFHkFMkBT52ysX7mLVqrxmn3ppswprZdfq+86kgD9TpdWhu9hqBl0sQZJlWULI29CVYN4Oz54YKDXmsPhAdrST8GI52K1LCx6g27EZy4rxVOgesZw2ctEQAWoW/gSTxRHyIR+NxT04TSVaMfcugviPOa0wCMYzvVnU6d4ib9KdhphSr9tk5hZj+8NY7mygqKw9McThyYSj5OdtD1FLoIvMxG/MVD2kVuhhJZcXF8AZP23Bxe1ZD1t+4e2n34f3uGM+m7q/venlNO9sNkkVKJm9kxGxkULgb2OZm5Hp4mMP+XqWRrAnzT8UooS7uptxDuWcR7axiw9hcukMaZ6JHXFMf7qWBFrB1iufLlBfUnxlCnwvMYoBecMbB8Impbi0Y0aoMFkneKODotIcu3zpvxYxLSjRL/Tewu8AuEeqcDP//uZOq2vZ4ZT51H5yHLx73WGEDG0LOlDSgBzyA97VvnpmIBwa7PHFqicemHUOgLWzhDSVngU8lgNMBVdANPdQ5n9VyAOtRPCtPIHkkrpxeK7fM="

install:
  - "pip install --upgrade pip setuptools"
  - "pip install --upgrade tox"
  - "pip install -r dev_requirements.txt"
  - "git fetch origin"

jobs:
  include:
    - env: "TOXENV=lint"
    - env: "TOXENV=check_release_file"
    - env: "TOXENV=py27"
      python: "2.7"
    - env: "TOXENV=py35"
      python: "3.5"
    - env: "TOXENV=py36"
      python: "3.6"
    - env: "TOXENV=deploy"
      stage: "deploy"

stages:
  - "test"
  - name: "deploy"
    if: "type = push"

script:
  - "tox"
