sudo: false
language: python

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

install:
  - "pip install --upgrade pip setuptools"
  - "pip install -r dev_requirements.txt"

script:
  - "coverage run -m py.test tests/*.py"
  - "coverage report"
